config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'log_out'

  resources :sessions, only: %i[create destroy]
  resources :schedules, only: [:index]
  resources :friends, only: [:index, :show, :edit] do
    get 'schedules', to: 'friends#schedules'
  end
  resources :users, only: [] do
    member do
      get :edit_line
      patch :update_line
    end
  end
  post "/linewebhook/callback", to: "linewebhook#callback"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @friends = current_user.friends
  end

  def show
    @friends = current_user.friends.find(params[:id])
  end

  def edit
    @friend = current_user.friends.find(params[:id])
  end

  def update
    @friend = current_user.friends.find(params[:id])
    if @friend.update(friend_params)
      redirect_to friends_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def schedules
    @friend = current_user.friends.find(params[:friend_id])

    service = Google::Apis::CalendarV3::CalendarService.new
    service = google_service_for(current_user)

    calendar_id = 'primary'
    response = service.list_events(calendar_id, max_results: 10, single_events: true, order_by: 'startTime', time_min: Time.now.iso8601)
    
    filtered_lessons = response.items.select do |schedule|
      schedule.summary.include?(@friend.real_name)
    end

    @schedules = filtered_lessons.map do |schedule|
      {
        summary: schedule.summary,
        start: (schedule.start.date || schedule.start.date_time).in_time_zone('Asia/Tokyo'),
        end: (schedule.end.date || schedule.end.date_time).in_time_zone('Asia/Tokyo')
      }
    end
  end

  private

  def friend_params
    params.require(:friend).permit(:real_name)
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.erb
<% if current_user %>
  <ul>
    <% current_user.friends.each do |friend| %>
      <%= form_with model: friend, url: friend_path(friend), method: :patch do |f| %>
        <div>
          <%= friend.line_display_name %>
          <%= f.label :real_name, "カレンダーで使っている名前" %>
          <%= link_to friend.real_name, friend_schedules_path(friend) %>
          <%= f.text_field :real_name %>
        </div>
        <%= f.submit "更新" %>
      <% end %>
    <% end %>
  </ul>
<% end %>

<%= link_to "TOPへ", root_path %>

app/views/friends/schedules.html.erb
<% @schedules.each do |schedule| %>
  <%= schedule[:summary] %>
  <%= schedule[:start].strftime("%m月%d日 %H:%M") %>
<% end %>

<%= link_to "友達一覧へ", friends_path %>